// Generated by gencpp from file rover_msgs/enc.msg
// DO NOT EDIT!


#ifndef ROVER_MSGS_MESSAGE_ENC_H
#define ROVER_MSGS_MESSAGE_ENC_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace rover_msgs
{
template <class ContainerAllocator>
struct enc_
{
  typedef enc_<ContainerAllocator> Type;

  enc_()
    : left(0)
    , right(0)  {
    }
  enc_(const ContainerAllocator& _alloc)
    : left(0)
    , right(0)  {
  (void)_alloc;
    }



   typedef int64_t _left_type;
  _left_type left;

   typedef int64_t _right_type;
  _right_type right;




  typedef boost::shared_ptr< ::rover_msgs::enc_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::rover_msgs::enc_<ContainerAllocator> const> ConstPtr;

}; // struct enc_

typedef ::rover_msgs::enc_<std::allocator<void> > enc;

typedef boost::shared_ptr< ::rover_msgs::enc > encPtr;
typedef boost::shared_ptr< ::rover_msgs::enc const> encConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::rover_msgs::enc_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::rover_msgs::enc_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace rover_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'sensor_msgs': ['/opt/ros/kinetic/share/sensor_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'rover_msgs': ['/home/achu/aurora2018/src/rover_msgs/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::rover_msgs::enc_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rover_msgs::enc_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rover_msgs::enc_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rover_msgs::enc_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rover_msgs::enc_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rover_msgs::enc_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::rover_msgs::enc_<ContainerAllocator> >
{
  static const char* value()
  {
    return "10ec03ad83d596042691890fad8ead6e";
  }

  static const char* value(const ::rover_msgs::enc_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x10ec03ad83d59604ULL;
  static const uint64_t static_value2 = 0x2691890fad8ead6eULL;
};

template<class ContainerAllocator>
struct DataType< ::rover_msgs::enc_<ContainerAllocator> >
{
  static const char* value()
  {
    return "rover_msgs/enc";
  }

  static const char* value(const ::rover_msgs::enc_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::rover_msgs::enc_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int64 left\n\
int64 right\n\
";
  }

  static const char* value(const ::rover_msgs::enc_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::rover_msgs::enc_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.left);
      stream.next(m.right);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct enc_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::rover_msgs::enc_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::rover_msgs::enc_<ContainerAllocator>& v)
  {
    s << indent << "left: ";
    Printer<int64_t>::stream(s, indent + "  ", v.left);
    s << indent << "right: ";
    Printer<int64_t>::stream(s, indent + "  ", v.right);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROVER_MSGS_MESSAGE_ENC_H
